// =============================================================================
// Scilab ( https://www.scilab.org/ ) - This file is part of Scilab
// Copyright (C) 2011 - DIGITEO - Michael Baudin
//
//  This file is distributed under the same license as the Scilab package.
// =============================================================================
// <-- CLI SHELL MODE -->
//
// <-- Non-regression test for bug 7093 -->
//
// <-- GitLab URL -->
// https://gitlab.com/scilab/scilab/-/issues/7093
//
// <-- Short Description -->
// The data structure generated by neldermead_new cannot be saved
// and reloaded.
//

nm = neldermead_new ();
save(fullfile(TMPDIR,"pb.dat"),"nm");
clear
load(fullfile(TMPDIR,"pb.dat"))
computed = exists("nm");
assert_checkequal(computed,1);
