// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: matchingblock.jflex

//CHECKSTYLE:OFF

package org.scilab.modules.scinotes;

import java.io.IOException;
import javax.swing.text.Element;

@javax.annotation.Generated("JFlex")

@SuppressWarnings("fallthrough")
public final class MatchingBlockScanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 256;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int LR = 2;
  public static final int RL = 4;
  public static final int OPENCLOSE = 6;
  public static final int CLOSEOPEN = 8;
  public static final int PSNART = 10;
  public static final int SPEC = 12;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6, 6
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\12\0\1\1\2\2\1\3\23\0\1\4\1\5\1\4"+
    "\1\6\1\7\1\0\1\10\1\11\1\12\5\0\1\13"+
    "\12\6\5\0\1\4\1\0\32\4\1\11\1\0\1\12"+
    "\1\0\1\4\1\0\1\14\1\4\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\2\4\1\24\1\25\1\26"+
    "\1\27\1\30\1\4\1\31\1\32\1\33\1\34\1\4"+
    "\1\35\1\4\1\36\1\4\1\11\1\0\1\12\7\0"+
    "\1\2\u01a2\0\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\7\0\6\1\1\2\1\3\15\1\1\4\1\3\11\1"+
    "\15\3\1\5\1\6\1\7\1\0\1\1\4\0\1\1"+
    "\1\0\5\1\1\2\6\1\16\0\1\3\16\0\1\2"+
    "\13\0\2\1\1\3\10\1\15\0\1\1\2\0\1\3"+
    "\11\0\1\3\10\0\13\1\23\0\1\2\12\0\11\1"+
    "\33\0\7\1\26\0\5\1\22\0\2\1\6\0\1\3"+
    "\6\0\1\1\1\0\1\1\3\0\1\1\4\0\1\1"+
    "\4\0\1\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[323];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\37\0\76\0\135\0\174\0\233\0\272\0\0"+
    "\0\331\0\370\0\u0117\0\u0136\0\u0155\0\0\0\u0174\0\u0193"+
    "\0\u01b2\0\u01d1\0\u01f0\0\u020f\0\u022e\0\u024d\0\u026c\0\u028b"+
    "\0\u02aa\0\u02c9\0\u02e8\0\u0307\0\u0155\0\0\0\u0326\0\u0345"+
    "\0\u0364\0\u0383\0\u03a2\0\u03c1\0\u03e0\0\u03ff\0\u041e\0\u043d"+
    "\0\u045c\0\u047b\0\u049a\0\u04b9\0\u04d8\0\u04f7\0\u0516\0\u0535"+
    "\0\u0554\0\u0573\0\u0592\0\u05b1\0\0\0\0\0\0\0\370"+
    "\0\u05d0\0\u05d0\0\u05ef\0\u0155\0\u060e\0\u060e\0\u062d\0\u064c"+
    "\0\u066b\0\u068a\0\u06a9\0\u06c8\0\u0136\0\u06e7\0\u0706\0\u0725"+
    "\0\u0744\0\u0763\0\u0782\0\u02e8\0\u07a1\0\u07c0\0\u07df\0\u07fe"+
    "\0\u081d\0\u083c\0\u085b\0\u087a\0\u0899\0\u08b8\0\u08d7\0\u08f6"+
    "\0\u0915\0\u0934\0\u0953\0\u0972\0\u0991\0\u09b0\0\u09cf\0\u09ee"+
    "\0\u0a0d\0\u0a2c\0\u0a4b\0\u0a6a\0\u0a89\0\u0aa8\0\u0ac7\0\u0ae6"+
    "\0\u0b05\0\u0b24\0\u0b43\0\u0b62\0\u0b81\0\u0ba0\0\u0bbf\0\u0bde"+
    "\0\u0bfd\0\u0c1c\0\u0c3b\0\u0c5a\0\u0c79\0\u0c98\0\u0cb7\0\u0cd6"+
    "\0\u0cf5\0\u0d14\0\u0d33\0\u0d52\0\u0d71\0\u0d90\0\u07a1\0\u0daf"+
    "\0\u0dce\0\u0ded\0\u0e0c\0\u0e2b\0\u0e4a\0\u0e69\0\u0e88\0\u0ea7"+
    "\0\u0ec6\0\u0ee5\0\u0f04\0\u0f23\0\u0f42\0\u0f61\0\u0f80\0\u0f9f"+
    "\0\u0fbe\0\u0fdd\0\u0ffc\0\u101b\0\u103a\0\u1059\0\u1078\0\u1097"+
    "\0\u10b6\0\u0b05\0\u10d5\0\u10f4\0\u1113\0\u1132\0\u1151\0\u1170"+
    "\0\u118f\0\u11ae\0\u11cd\0\u11ec\0\u120b\0\u122a\0\u1249\0\u1268"+
    "\0\u1287\0\u12a6\0\u12c5\0\u12e4\0\u1303\0\u1322\0\u1341\0\u1360"+
    "\0\u137f\0\u139e\0\u13bd\0\u13dc\0\u13fb\0\u141a\0\u1439\0\u1458"+
    "\0\u1477\0\u1496\0\u14b5\0\u14d4\0\u14f3\0\u1512\0\u1531\0\u1550"+
    "\0\u156f\0\u158e\0\u15ad\0\u15cc\0\u15eb\0\u160a\0\u1629\0\u1648"+
    "\0\u1667\0\u1686\0\u16a5\0\u16c4\0\u16e3\0\u1702\0\u1721\0\u1740"+
    "\0\u175f\0\u177e\0\u179d\0\u17bc\0\u17db\0\u17fa\0\u1819\0\u1838"+
    "\0\u1857\0\u1876\0\u1895\0\u18b4\0\u18d3\0\u18f2\0\u1911\0\u1930"+
    "\0\u194f\0\u196e\0\u198d\0\u19ac\0\u19cb\0\u19ea\0\u1a09\0\u1a28"+
    "\0\u1a47\0\u1a66\0\u1a85\0\u1aa4\0\u1ac3\0\u1ae2\0\u1b01\0\u1b20"+
    "\0\u1b3f\0\u1b5e\0\u1b7d\0\u1b9c\0\u1bbb\0\u1bda\0\u1bf9\0\u1c18"+
    "\0\u1c37\0\u1c56\0\u1c75\0\u1c94\0\u1cb3\0\u1cd2\0\u1cf1\0\u1d10"+
    "\0\u1d2f\0\u1d4e\0\u1d6d\0\u1d8c\0\u1dab\0\u1dca\0\u1de9\0\u1e08"+
    "\0\u1e27\0\u1e46\0\u1e65\0\u1e84\0\u1ea3\0\u1ec2\0\u1ee1\0\u1f00"+
    "\0\u1f1f\0\u1f3e\0\u1f5d\0\u1f7c\0\u1f9b\0\u1fba\0\u1fd9\0\u1ff8"+
    "\0\u2017\0\u2036\0\u2055\0\u2074\0\u2093\0\u04b9\0\u20b2\0\u20d1"+
    "\0\u20f0\0\u210f\0\u212e\0\u214d\0\u216c\0\u218b\0\u21aa\0\u21c9"+
    "\0\u21e8\0\u2207\0\u2226\0\u2245\0\u2264\0\u2283\0\u22a2\0\u22c1"+
    "\0\u22e0\0\u22ff\0\u231e\0\u233d\0\u235c\0\u237b\0\u239a\0\u23b9"+
    "\0\u23d8\0\u23f7\0\u2416\0\u23d8\0\u2435\0\u2454\0\u2473\0\u2492"+
    "\0\u24b1\0\u24d0\0\u0136";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[323];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\37\0\2\10\2\0\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\11\1\23\1\24"+
    "\2\11\1\25\1\11\1\26\2\11\1\27\1\11\1\30"+
    "\1\31\1\11\1\32\1\11\1\10\1\33\2\0\1\34"+
    "\1\12\1\34\1\10\1\35\1\36\1\16\1\10\2\34"+
    "\1\37\1\40\1\41\1\34\1\42\3\34\1\43\2\34"+
    "\1\44\1\45\1\46\2\34\1\47\2\36\2\0\5\36"+
    "\1\16\2\36\1\50\1\51\1\36\1\52\1\53\2\36"+
    "\1\54\1\36\1\55\2\36\1\56\1\36\1\57\1\60"+
    "\1\36\1\61\3\36\2\0\1\62\1\36\1\62\3\36"+
    "\1\16\1\36\2\62\1\63\7\62\1\64\10\62\10\0"+
    "\1\65\26\0\2\66\2\0\33\66\4\0\1\14\1\0"+
    "\1\14\1\0\1\67\3\0\23\14\1\70\1\0\1\70"+
    "\1\0\1\70\1\71\2\70\1\72\26\70\10\0\1\67"+
    "\6\0\1\73\23\0\1\14\1\0\1\14\5\0\23\14"+
    "\1\74\1\0\1\74\1\0\1\74\1\75\2\74\1\76"+
    "\26\74\10\0\1\67\41\0\1\77\27\0\1\14\1\0"+
    "\1\14\1\0\1\67\3\0\15\14\1\100\5\14\4\0"+
    "\1\14\1\0\1\14\1\0\1\67\3\0\10\14\1\101"+
    "\12\14\4\0\1\14\1\0\1\14\1\0\1\67\3\0"+
    "\12\14\1\102\10\14\4\0\1\14\1\0\1\14\1\0"+
    "\1\67\3\0\13\14\1\103\4\14\1\104\2\14\4\0"+
    "\1\14\1\0\1\14\1\0\1\67\3\0\4\14\1\105"+
    "\16\14\4\0\1\14\1\0\1\14\1\0\1\67\3\0"+
    "\3\14\1\106\17\14\4\0\1\14\1\0\1\14\1\0"+
    "\1\67\3\0\15\14\1\107\5\14\4\0\1\14\1\0"+
    "\1\14\1\0\1\67\3\0\3\14\1\110\15\14\1\111"+
    "\1\14\4\0\1\14\1\0\1\14\1\0\1\67\3\0"+
    "\15\14\1\112\5\14\4\0\1\14\1\0\1\14\1\0"+
    "\1\67\3\0\6\14\1\113\14\14\1\114\1\0\1\114"+
    "\1\0\7\114\1\115\23\114\16\0\1\116\1\117\1\120"+
    "\1\0\1\121\3\0\1\122\2\0\1\123\1\124\1\125"+
    "\2\0\1\126\16\0\1\116\1\117\1\120\1\0\1\121"+
    "\3\0\1\127\2\0\1\123\1\124\1\125\2\0\1\126"+
    "\16\0\1\116\1\117\1\120\1\0\1\121\1\0\1\130"+
    "\1\0\1\122\2\0\1\123\1\124\1\125\2\0\1\126"+
    "\16\0\1\116\1\131\1\120\1\0\1\121\1\132\2\0"+
    "\1\122\2\0\1\123\1\124\1\125\2\0\1\126\15\0"+
    "\1\133\1\116\1\117\1\120\1\0\1\121\3\0\1\122"+
    "\2\0\1\123\1\124\1\125\2\0\1\126\16\0\1\116"+
    "\1\117\1\120\1\0\1\121\3\0\1\122\1\134\1\0"+
    "\1\123\1\124\1\125\2\0\1\126\16\0\1\116\1\117"+
    "\1\120\1\0\1\121\3\0\1\122\1\135\1\0\1\123"+
    "\1\124\1\125\2\0\1\126\16\0\1\136\1\137\1\120"+
    "\1\0\1\121\3\0\1\122\2\0\1\123\1\124\1\140"+
    "\2\0\1\126\15\0\1\141\1\116\1\117\1\120\1\0"+
    "\1\121\3\0\1\122\2\0\1\123\1\124\1\125\2\0"+
    "\1\126\16\0\1\116\1\117\1\120\1\0\1\121\3\0"+
    "\1\122\2\0\1\142\1\124\1\125\2\0\1\126\31\0"+
    "\1\143\31\0\1\144\36\0\1\145\1\0\1\146\37\0"+
    "\1\147\4\0\1\150\22\0\1\151\35\0\1\152\50\0"+
    "\1\153\24\0\1\154\15\0\1\155\32\0\1\156\27\0"+
    "\1\157\32\0\1\160\7\0\1\161\26\0\1\160\7\0"+
    "\1\162\26\0\1\160\7\0\1\161\1\163\14\0\1\70"+
    "\2\0\1\70\54\0\1\164\15\0\1\74\2\0\1\74"+
    "\26\0\1\77\1\10\2\0\33\77\4\0\1\14\1\0"+
    "\1\14\5\0\5\14\1\165\15\14\4\0\1\14\1\0"+
    "\1\14\5\0\1\166\22\14\4\0\1\14\1\0\1\14"+
    "\5\0\2\14\1\167\15\14\1\170\2\14\4\0\1\14"+
    "\1\0\1\14\5\0\15\14\1\105\5\14\4\0\1\14"+
    "\1\0\1\14\5\0\12\14\1\171\10\14\4\0\1\14"+
    "\1\0\1\14\5\0\17\14\1\172\3\14\4\0\1\14"+
    "\1\0\1\14\5\0\13\14\1\173\7\14\4\0\1\14"+
    "\1\0\1\14\5\0\10\14\1\174\12\14\4\0\1\14"+
    "\1\0\1\14\5\0\7\14\1\175\13\14\4\0\1\14"+
    "\1\0\1\14\5\0\22\14\1\105\4\0\1\14\1\0"+
    "\1\14\5\0\7\14\1\176\13\14\1\114\1\0\1\114"+
    "\1\0\7\114\1\177\23\114\26\0\1\200\34\0\1\201"+
    "\31\0\1\202\3\0\1\10\30\0\1\203\50\0\1\204"+
    "\36\0\1\205\25\0\1\206\1\207\13\0\1\210\20\0"+
    "\1\211\52\0\1\212\24\0\1\16\7\0\1\204\32\0"+
    "\1\213\31\0\1\214\5\0\1\201\16\0\1\10\1\0"+
    "\1\10\5\0\3\10\1\215\17\10\33\0\1\216\26\0"+
    "\1\217\33\0\1\220\44\0\1\200\1\221\32\0\1\222"+
    "\1\201\27\0\1\211\10\0\1\223\27\0\1\224\46\0"+
    "\1\205\3\0\1\220\24\0\1\225\31\0\1\226\54\0"+
    "\1\227\40\0\1\230\33\0\1\151\33\0\1\231\14\0"+
    "\1\232\1\0\1\232\5\0\23\232\33\0\1\233\32\0"+
    "\1\234\33\0\1\235\35\0\1\236\51\0\1\151\23\0"+
    "\1\237\41\0\1\240\37\0\1\241\26\0\1\16\7\0"+
    "\1\241\32\0\1\242\31\0\1\243\24\0\1\14\1\0"+
    "\1\14\5\0\20\14\1\244\2\14\4\0\1\14\1\0"+
    "\1\14\5\0\16\14\1\245\4\14\4\0\1\14\1\0"+
    "\1\14\5\0\4\14\1\246\16\14\4\0\1\14\1\0"+
    "\1\14\5\0\11\14\1\247\11\14\4\0\1\14\1\0"+
    "\1\14\5\0\1\14\1\250\21\14\4\0\1\14\1\0"+
    "\1\14\5\0\6\14\1\251\14\14\4\0\1\14\1\0"+
    "\1\14\5\0\14\14\1\252\6\14\4\0\1\14\1\0"+
    "\1\14\5\0\3\14\1\253\17\14\4\0\1\14\1\0"+
    "\1\14\5\0\17\14\1\254\3\14\4\0\1\14\1\0"+
    "\1\14\5\0\10\14\1\255\12\14\17\0\1\10\42\0"+
    "\1\256\31\0\1\257\53\0\1\260\26\0\1\261\33\0"+
    "\1\10\45\0\1\262\32\0\1\263\41\0\1\264\27\0"+
    "\1\265\52\0\1\10\25\0\1\266\46\0\1\267\36\0"+
    "\1\270\27\0\1\271\46\0\1\272\7\0\1\10\1\0"+
    "\1\10\5\0\23\10\22\0\1\273\47\0\1\274\22\0"+
    "\1\275\43\0\1\276\46\0\1\277\34\0\1\300\23\0"+
    "\1\301\44\0\1\302\26\0\1\303\43\0\1\304\44\0"+
    "\1\305\25\0\1\306\52\0\1\307\27\0\1\310\31\0"+
    "\1\36\42\0\1\311\46\0\1\312\23\0\1\313\22\0"+
    "\1\14\1\0\1\14\5\0\11\14\1\314\11\14\4\0"+
    "\1\14\1\0\1\14\5\0\16\14\1\315\4\14\4\0"+
    "\1\14\1\0\1\14\5\0\20\14\1\316\2\14\4\0"+
    "\1\14\1\0\1\14\5\0\3\14\1\317\17\14\4\0"+
    "\1\14\1\0\1\14\5\0\17\14\1\320\3\14\4\0"+
    "\1\14\1\0\1\14\5\0\13\14\1\321\7\14\4\0"+
    "\1\14\1\0\1\14\5\0\3\14\1\322\17\14\4\0"+
    "\1\14\1\0\1\14\5\0\1\14\1\323\21\14\4\0"+
    "\1\14\1\0\1\14\5\0\1\14\1\324\21\14\4\0"+
    "\1\14\1\0\1\14\5\0\3\14\1\105\17\14\22\0"+
    "\1\325\46\0\1\326\27\0\1\327\46\0\1\330\25\0"+
    "\1\331\47\0\1\332\22\0\1\333\43\0\1\334\47\0"+
    "\1\220\33\0\1\335\30\0\1\200\47\0\1\336\15\0"+
    "\1\337\1\340\54\0\1\341\34\0\1\342\32\0\1\343"+
    "\30\0\1\336\44\0\1\344\43\0\1\345\27\0\1\346"+
    "\32\0\1\347\52\0\1\350\32\0\1\351\26\0\1\352"+
    "\34\0\1\353\36\0\1\354\40\0\1\151\52\0\1\355"+
    "\20\0\1\356\55\0\1\357\6\0\1\14\1\0\1\14"+
    "\5\0\3\14\1\360\17\14\4\0\1\14\1\0\1\14"+
    "\5\0\2\14\1\361\20\14\4\0\1\14\1\0\1\14"+
    "\5\0\12\14\1\362\10\14\4\0\1\14\1\0\1\14"+
    "\5\0\15\14\1\363\5\14\4\0\1\14\1\0\1\14"+
    "\5\0\7\14\1\364\13\14\4\0\1\14\1\0\1\14"+
    "\5\0\2\14\1\365\20\14\4\0\1\14\1\0\1\14"+
    "\5\0\15\14\1\366\5\14\4\0\1\14\1\0\1\14"+
    "\5\0\17\14\1\105\3\14\4\0\1\14\1\0\1\14"+
    "\5\0\6\14\1\105\14\14\35\0\1\10\33\0\1\367"+
    "\41\0\1\370\15\0\1\371\1\372\54\0\1\373\34\0"+
    "\1\374\32\0\1\375\30\0\1\370\33\0\1\376\54\0"+
    "\1\220\35\0\1\377\33\0\1\u0100\27\0\1\u0101\36\0"+
    "\1\u0102\53\0\1\u0103\21\0\1\u0104\35\0\1\u0105\40\0"+
    "\1\16\47\0\1\u0106\30\0\1\u0107\31\0\1\u0108\51\0"+
    "\1\u0109\40\0\1\151\25\0\1\151\31\0\1\u010a\47\0"+
    "\1\u010b\36\0\1\u010c\14\0\1\14\1\0\1\14\5\0"+
    "\12\14\1\u010d\10\14\4\0\1\14\1\0\1\14\5\0"+
    "\3\14\1\u010e\17\14\4\0\1\14\1\0\1\14\5\0"+
    "\1\14\1\u010f\21\14\4\0\1\14\1\0\1\14\5\0"+
    "\1\250\22\14\4\0\1\14\1\0\1\14\5\0\13\14"+
    "\1\u0110\7\14\4\0\1\14\1\0\1\14\5\0\16\14"+
    "\1\105\4\14\4\0\1\14\1\0\1\14\5\0\17\14"+
    "\1\u0111\3\14\14\0\1\u0112\54\0\1\10\35\0\1\u0113"+
    "\33\0\1\u0114\27\0\1\u0115\36\0\1\u0116\53\0\1\u0117"+
    "\26\0\1\u0118\31\0\1\u0119\53\0\1\u011a\27\0\1\220"+
    "\41\0\1\u011b\27\0\1\u011c\43\0\1\u011d\27\0\1\u011e"+
    "\33\0\1\303\51\0\1\u011f\41\0\1\151\37\0\1\u0120"+
    "\31\0\1\u0121\44\0\1\u0122\17\0\1\u0123\25\0\1\14"+
    "\1\0\1\14\5\0\17\14\1\365\3\14\4\0\1\14"+
    "\1\0\1\14\5\0\4\14\1\105\16\14\4\0\1\14"+
    "\1\0\1\14\5\0\17\14\1\u0124\3\14\4\0\1\14"+
    "\1\0\1\14\5\0\12\14\1\105\10\14\4\0\1\14"+
    "\1\0\1\14\5\0\7\14\1\u0125\13\14\24\0\1\u0126"+
    "\31\0\1\u0127\53\0\1\u0128\27\0\1\10\41\0\1\u0129"+
    "\27\0\1\u012a\32\0\1\220\46\0\1\u012b\31\0\1\u012c"+
    "\45\0\1\u012d\40\0\1\u012e\40\0\1\u0108\31\0\1\151"+
    "\33\0\1\u012f\47\0\1\u0130\22\0\1\u0131\51\0\1\u0132"+
    "\7\0\1\14\1\0\1\14\5\0\7\14\1\u0133\13\14"+
    "\4\0\1\14\1\0\1\14\5\0\3\14\1\365\17\14"+
    "\15\0\1\10\46\0\1\u0134\31\0\1\u0135\45\0\1\u0136"+
    "\40\0\1\u0137\41\0\1\u0138\6\0\1\10\1\0\1\10"+
    "\5\0\2\10\1\u0139\20\10\31\0\1\u013a\21\0\1\220"+
    "\41\0\1\u0108\37\0\1\u013b\34\0\1\u013c\43\0\1\u013d"+
    "\17\0\1\14\1\0\1\14\5\0\13\14\1\u013e\7\14"+
    "\34\0\1\116\20\0\1\116\51\0\1\u013f\21\0\1\10"+
    "\50\0\1\u0140\36\0\1\u0141\40\0\1\220\24\0\1\160"+
    "\47\0\1\u0142\13\0\1\14\1\0\1\14\5\0\12\14"+
    "\1\u0143\10\14\30\0\1\10\25\0\1\220\36\0\1\16"+
    "\45\0\1\10\10\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[9455];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\10\6\0\1\11\5\1\1\11\17\1\1\11\26\1"+
    "\3\11\1\0\1\1\4\0\1\1\1\0\14\1\16\0"+
    "\1\1\16\0\1\1\13\0\13\1\15\0\1\1\2\0"+
    "\1\1\11\0\1\1\10\0\13\1\23\0\1\1\12\0"+
    "\11\1\33\0\7\1\26\0\5\1\22\0\2\1\6\0"+
    "\1\1\6\0\1\1\1\0\1\1\3\0\1\1\4\0"+
    "\1\1\4\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[323];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private ScilabDocument doc;
    private Element elem;
    private boolean transp = false;
    private ScilabLexer scilabLexer;
    private int start;
    private int end;
    private int savePos;

    public MatchingBlockScanner(ScilabDocument doc) {
        this.doc = doc;
        this.elem = doc.getDefaultRootElement();
        this.scilabLexer = new ScilabLexer(doc, null, false);
    }

    public int yychar() {
        return (int) yychar;
    }

    public MatchingPositions getNextBlock(int pos, boolean lr) {
        int s = 1;
        transp = false;
	try {
      	    if (lr) {
                start =  pos;
                end = doc.getEndPosition().getOffset();
                yyreset(new ScilabDocumentReader(doc, start, end));
                yybegin(LR);
	    } else {
                start = pos - 1;
                end = 0;
                yyreset(new ScilabDocumentReader(doc, true, start, end));
              	yybegin(RL);
	    }
	    do {
               if (yylex() == 0) {
                  s--;
               } else {
                  s++;
               }
            } while (zzMarkedPos != 0 && s != 0);
        } catch (IOException e) {
            return null;
        }
        if (s == 0) {
            if (lr) {
                return new MatchingPositions(pos, pos, pos + yychar(), pos + yychar() + (transp?(yylength()-1):yylength()));
            } else {
                return new MatchingPositions(pos, pos, pos - yychar() - yylength(), pos - yychar());
            }
        }

        return null;
    }

    public MatchingPositions getMatchingBlock(int pos, boolean lr) {
        int p1, s = 1;
        transp = false;
        try {
            if (lr) {
                start =  pos;
                end = doc.getEndPosition().getOffset();
                yyreset(new ScilabDocumentReader(doc, start, end));
                yybegin(OPENCLOSE);
                if (yylex() != 1) {
                   return null;
                }

                p1 = pos + yylength();
                yybegin(LR);
            } else {
                 start = pos - 1;
                 end = 0;
                 yyreset(new ScilabDocumentReader(doc, true, start, end));
                 yybegin(CLOSEOPEN);
                 if (yylex() != 1) {
                    return null;
                 }
                 p1 = pos - yylength();
                 yybegin(RL);
            }

            do {
               if (yylex() == 0) {
                  s--;
               } else {
                  s++;
               }
            } while (zzMarkedPos != 0 && s != 0);
        } catch (IOException e) {
            return null;
        }
        if (s == 0) {
            if (lr) {
                return new MatchingPositions(pos, p1, pos + yychar(), pos + yychar() + (transp?(yylength()-1):yylength()));
            } else {
                return new MatchingPositions(p1, pos, pos - yychar() - yylength(), pos - yychar());
            }
        }

        return null;
    }

    public final class MatchingPositions {
        public int firstB;
        public int firstE;
        public int secondB;
        public int secondE;

        private MatchingPositions(int x1, int x2, int y1, int y2) {
            firstB = x1;
            firstE = x2;
            secondB = y1;
            secondE = y2;
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MatchingBlockScanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {   return -1;
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
          // fall through
          case 8: break;
          case 2:
            { return 1;
            }
          // fall through
          case 9: break;
          case 3:
            { return 0;
            }
          // fall through
          case 10: break;
          case 4:
            { yypushback(1);
                                   yybegin(PSNART);
            }
          // fall through
          case 11: break;
          case 5:
            { if (scilabLexer.getKeyword(start - yychar(), false) == ScilabLexerConstants.STRING) {
                                      savePos = start - yychar() - scilabLexer.beginString - scilabLexer.start;
                                      yybegin(SPEC);
                                   } else {
                                      yybegin(RL);
                                   }
            }
          // fall through
          case 12: break;
          case 6:
            { if (--savePos == 0) {
                                      yybegin(RL);
                                   }
            }
          // fall through
          case 13: break;
          case 7:
            { char c = yycharat(yylength() - 2);
                                   if (c == ')' || c == ']' || c == '}') {
                                      transp = true;
                                      return 0;
                                   }
            }
          // fall through
          case 14: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
