/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.xcos;

public class JavaSSPResourceJNI {
  public final static native int save(String jarg1, long jarg2);
  public final static native int load(String jarg1, long jarg2);
}
