/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.xcos;

public class JavaSSPResource {
  public static int save(String uri, long id) {
    return JavaSSPResourceJNI.save(uri, id);
  }

  public static int load(String uri, long id) {
    return JavaSSPResourceJNI.load(uri, id);
  }

}
