/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.xcos;

import java.util.Map;
import java.util.TreeMap;

public class JavaController extends Controller {
  public static int port_from_property(ObjectProperties p) {
    return JavaControllerJNI.port_from_property(p.ordinal());
  }

  public static ObjectProperties property_from_port(PortKind p) {
    return ObjectProperties.class.getEnumConstants()[JavaControllerJNI.property_from_port(p.ordinal())];
  }

  public static ObjectProperties opposite_property(ObjectProperties prop) {
    return ObjectProperties.class.getEnumConstants()[JavaControllerJNI.opposite_property(prop.ordinal())];
  }

  public static PortKind opposite_port(PortKind p) {
    return PortKind.class.getEnumConstants()[JavaControllerJNI.opposite_port(p.ordinal())];
  }


  // will contain all registered JavaViews to prevent garbage-collection
  private static Map<String, View> references = new TreeMap<String, View>();

  private static long add_reference(String name, View v) {
    references.put(name, v);
    return View.getCPtr(v);
  }

  private static View remove_reference(View v) {
    references.values().remove(v);
    return v;
  }

  public static View lookup_view(String name) {
    return references.get(name);
  }

  public static void register_view(String name, View view) {
    JavaControllerJNI.register_view(name, add_reference(name, view), view);
  }

  public static void unregister_view(View view) {
    JavaControllerJNI.unregister_view(View.getCPtr(view), view);
    remove_reference(view);
  }

}
