/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.xcos;

public class View {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected View(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(View obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(View obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JavaControllerJNI.delete_View(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    JavaControllerJNI.View_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    JavaControllerJNI.View_change_ownership(this, swigCPtr, true);
  }

  @SuppressWarnings("this-escape")
  public View() {
    this(JavaControllerJNI.new_View(), true);
    JavaControllerJNI.View_director_connect(this, swigCPtr, true, true);
  }

  public void objectCreated(long uid, Kind kind) {
    JavaControllerJNI.View_objectCreated(swigCPtr, this, uid, kind.ordinal());
  }

  public void objectReferenced(long uid, Kind kind, long refCount) {
    JavaControllerJNI.View_objectReferenced(swigCPtr, this, uid, kind.ordinal(), refCount);
  }

  public void objectUnreferenced(long uid, Kind kind, long refCount) {
    JavaControllerJNI.View_objectUnreferenced(swigCPtr, this, uid, kind.ordinal(), refCount);
  }

  public void objectDeleted(long uid, Kind kind) {
    JavaControllerJNI.View_objectDeleted(swigCPtr, this, uid, kind.ordinal());
  }

  public void objectCloned(long uid, long cloned, Kind kind) {
    JavaControllerJNI.View_objectCloned(swigCPtr, this, uid, cloned, kind.ordinal());
  }

  public void propertyUpdated(long uid, Kind kind, ObjectProperties property, UpdateStatus status) {
    JavaControllerJNI.View_propertyUpdated(swigCPtr, this, uid, kind.ordinal(), property.ordinal(), status.ordinal());
  }

}
