/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.ui_data;


 /** 
   * ui_data management 
   * @author Vincent COUVERT
   * @author Allan CORNET
   * @copyright INRIA 
   */
public class UI_data {

  /**
    * Constructor
    */
  protected UI_data() {
    throw new UnsupportedOperationException();
  }
  public static void putScilabVariable(String name, String[] lines, int rows, int cols) {
    UI_dataJNI.putScilabVariable(name, lines, rows, cols);
  }

  
    /**
    * Put a scilab variable as an array of strings in C envrionment
    * @param lines array of string
    * @param rows the number of rows
    * @param cols the number of cols
    */
public static String getUnnamedVariable() {
    return UI_dataJNI.getUnnamedVariable();
  }

}
