// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: modules/helptools/src/java/jflex/scilab.jflex

//CHECKSTYLE:OFF

package org.scilab.modules.helptools.scilab;

import java.util.Set;
import java.util.HashSet;
import java.util.List;
import java.util.ArrayList;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.Reader;
import java.io.StringReader;
import java.io.IOException;

@javax.annotation.Generated("JFlex")

@SuppressWarnings("fallthrough")
public final class ScilabLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int QSTRING = 2;
  public static final int COMMENT = 4;
  public static final int FIELD = 6;
  public static final int COMMANDS = 8;
  public static final int COMMANDSWHITE = 10;
  public static final int FUNCTION = 12;
  public static final int TYPEID = 14;
  public static final int FUNNAME = 16;
  public static final int RETS = 18;
  public static final int ARGS = 20;
  public static final int BREAKINARGS = 22;
  public static final int WHITESEOL = 24;
  public static final int CLEANFIRST = 26;
  public static final int CLEAN = 28;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\1\0\10\1\1\2\1\3\2\4\1\5\22\1\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\21\1\23\1\24\12\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\7\1\33\2\11"+
    "\1\34\1\35\1\36\1\37\1\11\1\40\1\41\3\11"+
    "\1\42\1\11\1\43\1\44\1\11\1\45\1\46\1\47"+
    "\2\11\1\50\3\11\1\51\1\52\1\53\1\54\1\7"+
    "\1\1\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\11\1\66\1\67\1\70\1\71\1\72"+
    "\1\73\1\74\1\75\1\76\1\77\1\100\1\11\1\101"+
    "\1\102\1\103\1\37\1\104\1\105\1\106\1\33\6\1"+
    "\1\4\u01a2\1\2\4\326\1\u0100\4";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\15\0\1\2\1\3\1\4\2\5\1\6"+
    "\1\7\1\10\1\11\1\7\1\12\1\13\1\14\1\15"+
    "\2\16\1\17\1\16\1\20\1\11\1\21\1\16\1\22"+
    "\22\7\2\1\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\30\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\37\1\41\1\42\1\43\1\1\1\44\1\45"+
    "\2\37\1\46\1\37\1\47\1\50\1\51\1\37\1\52"+
    "\1\50\1\53\1\37\1\54\1\37\1\50\1\55\1\37"+
    "\1\56\1\37\1\57\1\60\1\61\1\62\1\37\1\63"+
    "\2\37\2\64\1\45\1\37\2\65\1\66\1\50\1\67"+
    "\1\70\1\71\3\72\2\7\1\0\1\73\1\16\1\11"+
    "\1\16\1\20\1\74\1\20\1\75\1\76\1\77\11\7"+
    "\1\100\17\7\4\0\1\101\3\0\1\102\1\0\1\103"+
    "\3\7\1\20\1\72\12\7\1\100\15\7\1\104\7\7"+
    "\1\100\2\7\1\105\53\7\1\106\1\107\1\7\1\110";

  private static int [] zzUnpackAction() {
    int [] result = new int[258];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\107\0\216\0\325\0\u011c\0\u0163\0\u01aa\0\u01f1"+
    "\0\u0238\0\u027f\0\u02c6\0\u030d\0\u0354\0\u039b\0\u03e2\0\u0429"+
    "\0\u0429\0\u0429\0\u0429\0\u0470\0\u0429\0\u04b7\0\u0429\0\u04b7"+
    "\0\u04fe\0\u0545\0\u0429\0\u0429\0\u0429\0\u058c\0\u0429\0\u05d3"+
    "\0\u061a\0\u0661\0\u0429\0\u06a8\0\u06ef\0\u0736\0\u077d\0\u07c4"+
    "\0\u080b\0\u0852\0\u0899\0\u08e0\0\u0927\0\u096e\0\u09b5\0\u09fc"+
    "\0\u0a43\0\u0a8a\0\u0ad1\0\u0b18\0\u0b5f\0\u0ba6\0\u0bed\0\u0c34"+
    "\0\u0c7b\0\u0429\0\u0cc2\0\u0429\0\u0cc2\0\u0429\0\u0429\0\u0d09"+
    "\0\u0429\0\u0d50\0\u0429\0\u0429\0\u0429\0\u0429\0\u0429\0\u0429"+
    "\0\u0d97\0\u0d97\0\u0dde\0\u0dde\0\u0429\0\u0e25\0\u0429\0\u0429"+
    "\0\u0e6c\0\u0eb3\0\u0efa\0\u0efa\0\u0429\0\u0f41\0\u0429\0\u0f88"+
    "\0\u0429\0\u0fcf\0\u1016\0\u1016\0\u0429\0\u105d\0\u10a4\0\u10eb"+
    "\0\u10eb\0\u0429\0\u1132\0\u0429\0\u0429\0\u0429\0\u1179\0\u1179"+
    "\0\u0429\0\u11c0\0\u1207\0\u0429\0\u124e\0\u1207\0\u1295\0\u0429"+
    "\0\u12dc\0\u1323\0\u136a\0\u0429\0\u13b1\0\u13f8\0\u04b7\0\u143f"+
    "\0\u1486\0\u14cd\0\u1514\0\u0545\0\u0429\0\u155b\0\u15a2\0\u15e9"+
    "\0\u1630\0\u0429\0\u1677\0\u0429\0\u0429\0\u0429\0\u16be\0\u1705"+
    "\0\u174c\0\u1793\0\u17da\0\u1821\0\u1868\0\u18af\0\u18f6\0\u04b7"+
    "\0\u193d\0\u1984\0\u19cb\0\u1a12\0\u1a59\0\u1aa0\0\u1ae7\0\u1b2e"+
    "\0\u1b75\0\u1bbc\0\u1c03\0\u1c4a\0\u1c91\0\u1cd8\0\u1d1f\0\u0cc2"+
    "\0\u0dde\0\u0f41\0\u0f88\0\u0429\0\u0fcf\0\u105d\0\u1d66\0\u11c0"+
    "\0\u1207\0\u0429\0\u1dad\0\u1df4\0\u1e3b\0\u1e82\0\u1ec9\0\u1f10"+
    "\0\u1f57\0\u1f9e\0\u1fe5\0\u202c\0\u2073\0\u20ba\0\u2101\0\u2148"+
    "\0\u218f\0\u21d6\0\u221d\0\u2264\0\u22ab\0\u22f2\0\u2339\0\u2380"+
    "\0\u23c7\0\u240e\0\u2455\0\u249c\0\u24e3\0\u252a\0\u2571\0\u0429"+
    "\0\u25b8\0\u25ff\0\u2646\0\u268d\0\u26d4\0\u271b\0\u2762\0\u27a9"+
    "\0\u27f0\0\u2837\0\u04b7\0\u287e\0\u28c5\0\u290c\0\u2953\0\u299a"+
    "\0\u29e1\0\u2a28\0\u2a6f\0\u2ab6\0\u2afd\0\u2b44\0\u2b8b\0\u2bd2"+
    "\0\u2c19\0\u2c60\0\u2ca7\0\u2cee\0\u2d35\0\u2d7c\0\u2dc3\0\u2e0a"+
    "\0\u2e51\0\u2e98\0\u2edf\0\u2f26\0\u2f6d\0\u2fb4\0\u2ffb\0\u3042"+
    "\0\u3089\0\u30d0\0\u3117\0\u315e\0\u31a5\0\u31ec\0\u3233\0\u327a"+
    "\0\u32c1\0\u3308\0\u334f\0\u3396\0\u33dd\0\u3424\0\u346b\0\u0429"+
    "\0\u34b2\0\u04b7";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[258];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\20\1\21\1\22\1\23\1\0\1\24\1\25\1\26"+
    "\1\27\1\26\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\21\1\40\1\41\1\42\1\43\1\21"+
    "\1\44\1\45\1\46\1\45\12\26\1\47\1\50\1\51"+
    "\1\34\1\37\1\35\1\37\1\52\1\53\1\54\1\55"+
    "\1\56\1\57\2\26\1\60\2\26\1\61\1\26\1\62"+
    "\1\63\1\64\1\65\1\66\1\67\1\26\1\70\2\26"+
    "\1\34\1\37\1\35\2\71\1\72\1\23\1\71\1\24"+
    "\2\71\1\73\3\71\1\74\1\75\12\71\1\76\1\71"+
    "\1\77\54\71\1\20\2\100\1\101\1\100\1\102\2\100"+
    "\1\103\3\100\1\104\1\105\12\100\1\106\1\100\1\107"+
    "\54\100\3\110\1\23\1\0\1\24\1\110\1\111\1\110"+
    "\1\111\1\112\1\111\20\110\15\111\4\110\27\111\5\110"+
    "\1\113\1\23\1\0\1\24\1\114\7\110\1\115\70\110"+
    "\2\116\1\117\1\23\1\116\1\24\1\120\5\116\1\74"+
    "\5\116\1\110\1\116\1\121\2\116\1\110\1\76\1\116"+
    "\1\77\54\116\4\110\1\0\1\122\1\110\1\123\1\110"+
    "\1\123\1\124\1\123\20\110\15\123\1\125\3\110\27\123"+
    "\5\110\1\126\1\110\1\0\1\122\1\126\7\110\1\127"+
    "\5\110\1\130\4\110\1\131\57\110\1\132\1\110\1\0"+
    "\1\122\1\132\1\133\1\110\1\133\1\134\1\133\2\110"+
    "\1\135\5\110\1\136\7\110\15\133\4\110\27\133\5\110"+
    "\1\137\1\110\1\0\1\122\1\137\1\140\1\110\1\140"+
    "\1\141\1\140\6\110\1\142\1\143\5\110\1\144\2\110"+
    "\15\140\1\145\1\110\1\146\1\110\27\140\5\110\1\137"+
    "\1\110\1\0\1\122\1\137\1\147\1\110\1\147\1\150"+
    "\1\147\3\110\1\151\2\110\1\142\1\152\10\110\15\147"+
    "\4\110\27\147\5\110\1\153\1\154\1\0\1\155\1\156"+
    "\15\110\1\157\62\110\4\160\1\0\1\161\1\120\100\160"+
    "\2\110\1\162\1\163\1\0\1\163\1\162\100\110\2\164"+
    "\1\165\1\166\1\0\1\166\1\165\100\164\112\0\1\23"+
    "\112\0\1\26\1\0\2\26\12\0\1\26\6\0\15\26"+
    "\4\0\27\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\3\26\1\167\7\26\1\167\1\26\4\0\4\26"+
    "\1\170\1\167\2\26\1\171\3\26\1\172\1\26\1\173"+
    "\2\26\2\167\4\26\14\0\1\174\13\0\1\174\1\0"+
    "\1\21\4\0\15\174\4\0\27\174\23\0\1\37\103\0"+
    "\1\175\2\0\1\176\2\0\1\177\1\200\1\201\24\0"+
    "\1\200\1\0\1\37\55\0\1\37\1\202\105\0\1\201"+
    "\1\0\1\42\7\0\2\203\21\0\2\203\56\0\1\204"+
    "\1\205\105\0\1\37\106\0\1\206\64\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\1\207\14\26\4\0\27\26"+
    "\12\0\1\26\1\0\2\26\12\0\1\26\6\0\6\26"+
    "\1\210\6\26\4\0\27\26\12\0\1\26\1\0\2\26"+
    "\12\0\1\26\6\0\12\26\1\211\2\26\4\0\27\26"+
    "\12\0\1\26\1\0\2\26\12\0\1\26\6\0\15\26"+
    "\4\0\1\26\1\212\16\26\1\213\6\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\20\26"+
    "\1\214\6\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\1\215\11\26\1\216\2\26\1\217"+
    "\11\26\12\0\1\26\1\0\2\26\12\0\1\26\6\0"+
    "\15\26\4\0\15\26\1\220\11\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\12\26\1\221"+
    "\1\26\1\222\10\26\1\223\1\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\15\26\1\224"+
    "\5\26\1\225\3\26\12\0\1\26\1\0\2\26\12\0"+
    "\1\26\6\0\15\26\4\0\5\26\1\220\21\26\12\0"+
    "\1\26\1\0\2\26\12\0\1\26\6\0\15\26\4\0"+
    "\4\26\1\226\22\26\12\0\1\26\1\0\2\26\12\0"+
    "\1\26\6\0\15\26\4\0\22\26\1\227\4\26\12\0"+
    "\1\26\1\0\2\26\12\0\1\26\6\0\15\26\4\0"+
    "\1\230\17\26\1\231\6\26\12\0\1\26\1\0\2\26"+
    "\12\0\1\26\6\0\15\26\4\0\23\26\1\223\3\26"+
    "\12\0\1\26\1\0\2\26\12\0\1\26\6\0\15\26"+
    "\4\0\4\26\1\232\22\26\12\0\1\26\1\0\2\26"+
    "\12\0\1\26\6\0\15\26\4\0\4\26\1\233\17\26"+
    "\1\234\2\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\7\26\1\235\10\26\1\236\6\26"+
    "\12\0\1\26\1\0\2\26\12\0\1\26\6\0\15\26"+
    "\4\0\7\26\1\237\17\26\3\0\2\71\2\0\1\71"+
    "\1\0\2\71\1\240\3\71\1\0\1\240\12\71\1\0"+
    "\1\71\1\0\54\71\10\0\1\71\4\0\1\71\72\0"+
    "\2\100\1\0\4\100\1\0\3\100\2\0\12\100\1\0"+
    "\1\100\1\0\54\100\1\0\2\100\1\101\4\100\1\0"+
    "\3\100\2\0\12\100\1\0\1\100\1\0\54\100\7\0"+
    "\1\111\1\0\2\111\12\0\1\111\6\0\15\111\4\0"+
    "\27\111\5\0\1\241\3\0\1\241\7\0\1\115\70\0"+
    "\2\116\2\0\1\116\2\0\5\116\1\0\5\116\1\0"+
    "\1\116\1\0\2\116\2\0\1\116\1\0\56\116\2\0"+
    "\1\116\2\0\5\116\1\0\5\116\1\0\1\116\1\202"+
    "\2\116\2\0\1\116\1\0\54\116\3\0\1\110\112\0"+
    "\1\123\1\0\2\123\12\0\1\123\6\0\15\123\4\0"+
    "\27\123\5\0\1\242\3\0\1\242\15\0\1\243\106\0"+
    "\1\244\64\0\1\245\3\0\1\245\15\0\1\246\71\0"+
    "\1\133\1\0\2\133\12\0\1\133\6\0\15\133\4\0"+
    "\27\133\27\0\1\115\64\0\1\137\3\0\1\137\107\0"+
    "\1\140\1\0\2\140\12\0\1\140\6\0\15\140\4\0"+
    "\27\140\26\0\1\247\72\0\1\147\1\0\2\147\12\0"+
    "\1\147\6\0\15\147\4\0\27\147\26\0\1\250\65\0"+
    "\1\251\1\154\1\0\1\155\1\251\103\0\1\154\127\0"+
    "\1\252\65\0\1\160\105\0\1\162\1\163\1\0\1\163"+
    "\1\162\103\0\1\163\1\0\1\163\103\0\1\165\3\0"+
    "\1\165\103\0\1\166\1\0\1\166\110\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\16\26\1\253"+
    "\10\26\12\0\1\26\1\0\2\26\12\0\1\26\6\0"+
    "\15\26\4\0\14\26\1\254\12\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\1\255\26\26"+
    "\12\0\1\26\1\0\2\26\12\0\1\26\6\0\15\26"+
    "\4\0\10\26\1\167\16\26\23\0\1\37\2\0\1\37"+
    "\106\0\1\177\106\0\1\37\110\0\1\201\7\0\2\203"+
    "\21\0\2\203\46\0\1\256\3\0\1\256\70\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\5\26\1\257\7\26"+
    "\4\0\27\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\10\26\1\260\4\26\4\0\27\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\1\261\14\26\4\0"+
    "\27\26\12\0\1\26\1\0\2\26\12\0\1\26\6\0"+
    "\15\26\4\0\15\26\1\262\11\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\6\26\1\263"+
    "\20\26\12\0\1\26\1\0\2\26\12\0\1\26\6\0"+
    "\15\26\4\0\4\26\1\264\22\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\21\26\1\265"+
    "\1\266\4\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\1\267\26\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\14\26\1\270"+
    "\12\26\12\0\1\26\1\0\2\26\12\0\1\26\6\0"+
    "\15\26\4\0\21\26\1\271\5\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\3\26\1\272"+
    "\17\26\1\273\3\26\12\0\1\26\1\0\2\26\12\0"+
    "\1\26\6\0\15\26\4\0\10\26\1\274\16\26\12\0"+
    "\1\26\1\0\2\26\12\0\1\26\6\0\15\26\4\0"+
    "\20\26\1\220\6\26\12\0\1\26\1\0\2\26\12\0"+
    "\1\26\6\0\15\26\4\0\14\26\1\275\12\26\12\0"+
    "\1\26\1\0\2\26\12\0\1\26\6\0\15\26\4\0"+
    "\22\26\1\276\4\26\12\0\1\26\1\0\2\26\12\0"+
    "\1\26\6\0\15\26\4\0\7\26\1\277\17\26\12\0"+
    "\1\26\1\0\2\26\12\0\1\26\6\0\15\26\4\0"+
    "\23\26\1\300\3\26\12\0\1\26\1\0\2\26\12\0"+
    "\1\26\6\0\15\26\4\0\15\26\1\301\11\26\12\0"+
    "\1\26\1\0\2\26\12\0\1\26\6\0\15\26\4\0"+
    "\21\26\1\302\1\303\4\26\12\0\1\26\1\0\2\26"+
    "\12\0\1\26\6\0\15\26\4\0\12\26\1\304\14\26"+
    "\12\0\1\26\1\0\2\26\12\0\1\26\6\0\15\26"+
    "\4\0\10\26\1\305\16\26\12\0\1\26\1\0\2\26"+
    "\12\0\1\26\6\0\15\26\4\0\4\26\1\306\22\26"+
    "\12\0\1\26\1\0\2\26\12\0\1\26\6\0\15\26"+
    "\4\0\26\26\1\220\12\0\1\26\1\0\2\26\12\0"+
    "\1\26\6\0\15\26\4\0\10\26\1\307\16\26\26\0"+
    "\1\310\72\0\1\26\1\0\2\26\12\0\1\26\6\0"+
    "\15\26\4\0\21\26\1\167\5\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\5\26\1\167"+
    "\21\26\12\0\1\26\1\0\2\26\12\0\1\26\6\0"+
    "\15\26\4\0\14\26\1\167\12\26\30\0\1\256\70\0"+
    "\1\26\1\0\2\26\12\0\1\26\6\0\4\26\1\311"+
    "\10\26\4\0\27\26\12\0\1\26\1\0\2\26\12\0"+
    "\1\26\6\0\1\26\1\312\13\26\4\0\27\26\12\0"+
    "\1\26\1\0\2\26\12\0\1\26\6\0\5\26\1\167"+
    "\7\26\4\0\27\26\12\0\1\26\1\0\2\26\12\0"+
    "\1\26\6\0\15\26\4\0\20\26\1\274\6\26\12\0"+
    "\1\26\1\0\2\26\12\0\1\26\6\0\15\26\4\0"+
    "\23\26\1\313\3\26\12\0\1\26\1\0\2\26\12\0"+
    "\1\26\6\0\15\26\4\0\1\314\26\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\4\26"+
    "\1\220\22\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\2\26\1\315\24\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\21\26"+
    "\1\316\5\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\22\26\1\317\4\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\4\26"+
    "\1\320\22\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\5\26\1\321\21\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\13\26"+
    "\1\322\13\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\22\26\1\323\4\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\2\26"+
    "\1\324\24\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\7\26\1\325\17\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\4\26"+
    "\1\326\22\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\21\26\1\327\5\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\16\26"+
    "\1\330\10\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\23\26\1\331\3\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\23\26"+
    "\1\332\3\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\4\26\1\333\22\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\22\26"+
    "\1\266\4\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\14\26\1\220\12\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\12\26"+
    "\1\265\14\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\7\26\1\334\5\26\4\0\27\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\5\26\1\335\7\26"+
    "\4\0\27\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\13\26\1\336\13\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\11\26"+
    "\1\323\15\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\7\26\1\220\17\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\21\26"+
    "\1\337\5\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\10\26\1\340\16\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\10\26"+
    "\1\60\16\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\23\26\1\341\3\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\4\26"+
    "\1\342\22\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\22\26\1\343\4\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\15\26"+
    "\1\344\11\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\20\26\1\345\6\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\4\26"+
    "\1\323\22\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\4\26\1\346\22\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\13\26"+
    "\1\327\13\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\20\26\1\347\6\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\2\26"+
    "\1\350\24\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\6\26\1\351\6\26\4\0\27\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\11\26\1\167\3\26"+
    "\4\0\27\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\4\26\1\352\22\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\3\26"+
    "\1\353\23\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\14\26\1\354\12\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\14\26"+
    "\1\355\12\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\20\26\1\356\6\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\10\26"+
    "\1\357\16\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\3\26\1\360\23\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\24\26"+
    "\1\361\2\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\20\26\1\362\6\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\14\26"+
    "\1\323\12\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\22\26\1\220\4\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\2\26\1\167\12\26"+
    "\4\0\27\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\14\26\1\363\12\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\4\26"+
    "\1\60\22\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\23\26\1\327\3\26\12\0\1\26"+
    "\1\0\2\26\12\0\1\26\6\0\15\26\4\0\2\26"+
    "\1\364\24\26\12\0\1\26\1\0\2\26\12\0\1\26"+
    "\6\0\15\26\4\0\1\365\26\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\15\26\1\366"+
    "\11\26\12\0\1\26\1\0\2\26\12\0\1\26\6\0"+
    "\15\26\4\0\21\26\1\220\5\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\10\26\1\367"+
    "\16\26\12\0\1\26\1\0\2\26\12\0\1\26\6\0"+
    "\15\26\4\0\22\26\1\370\4\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\22\26\1\360"+
    "\4\26\12\0\1\26\1\0\2\26\12\0\1\26\6\0"+
    "\15\26\4\0\22\26\1\371\4\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\22\26\1\372"+
    "\4\26\12\0\1\26\1\0\2\26\12\0\1\26\6\0"+
    "\15\26\4\0\14\26\1\373\12\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\21\26\1\265"+
    "\5\26\12\0\1\26\1\0\2\26\12\0\1\26\6\0"+
    "\15\26\4\0\10\26\1\374\16\26\12\0\1\26\1\0"+
    "\2\26\12\0\1\26\6\0\15\26\4\0\10\26\1\375"+
    "\16\26\12\0\1\26\1\0\2\26\12\0\1\26\6\0"+
    "\15\26\4\0\10\26\1\376\16\26\5\0\1\377\3\0"+
    "\1\377\1\26\1\0\2\26\12\0\1\26\6\0\15\26"+
    "\1\u0100\3\0\27\26\12\0\1\26\1\0\2\26\12\0"+
    "\1\26\6\0\15\26\4\0\4\26\1\360\22\26\12\0"+
    "\1\26\1\0\2\26\12\0\1\26\6\0\15\26\4\0"+
    "\15\26\1\u0101\11\26\12\0\1\26\1\0\2\26\12\0"+
    "\1\26\6\0\15\26\4\0\15\26\1\306\11\26\5\0"+
    "\1\377\3\0\1\377\107\0\1\26\1\0\2\26\12\0"+
    "\1\26\6\0\15\26\4\0\14\26\1\u0102\12\26\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[13561];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\15\0\4\11\1\1\1\11\1\1\1\11"+
    "\3\1\3\11\1\1\1\11\3\1\1\11\26\1\1\11"+
    "\1\1\1\11\1\1\2\11\1\1\1\11\1\1\6\11"+
    "\4\1\1\11\1\1\2\11\4\1\1\11\1\1\1\11"+
    "\1\1\1\11\3\1\1\11\4\1\1\11\1\1\3\11"+
    "\2\1\1\11\2\1\1\11\3\1\1\11\3\1\1\11"+
    "\7\1\1\0\1\11\4\1\1\11\1\1\3\11\31\1"+
    "\4\0\1\11\3\0\1\1\1\0\1\11\35\1\1\11"+
    "\67\1\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[258];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private static Set<String> commands;
    private static Set<String> macros;

    private boolean transposable;
    private boolean breakstring;
    private boolean breakargs;
    private int whitesOnFirstLine;
    private int saveLexState;

    private String id;
    private List<String> returnValues = new ArrayList<String>();
    private List<String> argsValues = new ArrayList<String>();
    private List<String> localFun = new ArrayList<String>();

    private AbstractScilabCodeHandler handler;

    public ScilabLexer(String[] primFile, String[] macroFile) {
       if (commands == null) {
          commands = new HashSet<String>();
          macros = new HashSet<String>();
          loadNames(primFile, commands);
          loadNames(macroFile, macros);
       }
    }

    public ScilabLexer(String primFile, String macroFile) {
       this(new String[]{primFile}, new String[]{macroFile});
    }

    public ScilabLexer(Set<String> primitives, Set<String> _macros) {
       commands = primitives;
       macros = _macros;
    }

    private void loadNames(String[] files, Set<String> set) {
       for (int i = 0; i < files.length; i++) {
          loadNames(files[i], set);
       }
    }

    private void loadNames(String file, Set<String> set) {
       if (file == null) {
          return;
       }
       BufferedReader input = null;
       try {
          input = new BufferedReader(new FileReader(file));
          String line = null;
          while ((line = input.readLine()) != null) {
             set.add(line);
          }
       } catch (IOException e) {
          System.err.println(e);
       }
       if (input != null) {
          try {
             input.close();
          } catch (IOException e) {
             System.err.println(e);
          }
       }
    }

    private String trimEnd(String str) {
        int end = str.length() - 1;
        int i = end;
        for (; i >= 0; i--) {
           char c = str.charAt(i);
           if (c != ' ' && c != '\t' && c != '\r' && c != '\n') {
              break;
           }
        }
        if (i != end) {
           return str.substring(0, i + 1);
        }

        return str;
    }

    public String convert(AbstractScilabCodeHandler h, String code) {
        Reader reader = new StringReader(trimEnd(code));
        String str = convert(h, reader, true);
        try {
          reader.close();
        } catch (IOException e) { }

        return str;
    }

    public String convert(AbstractScilabCodeHandler h, Reader code, boolean ret) {
        if (code == null) {
           return null;
        } else {
           handler = h;
           transposable = false;
           breakargs = false;
           whitesOnFirstLine = 0;
           localFun.clear();
           yyreset(code);
           yybegin(CLEANFIRST);
           try {
               yylex();
           } catch (IOException e) {
               return null;
           }
           if (ret) {
               return h.toString();
           }
           return "";
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ScilabLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public void yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return;
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { handler.handleString(yytext());
            }
          // fall through
          case 73: break;
          case 2:
            { return;
            }
          // fall through
          case 74: break;
          case 3:
            { transposable = false;
                                   handler.handleDefault(yytext());
            }
          // fall through
          case 75: break;
          case 4:
            { transposable = false;
                                   handler.handleNothing("    ");
            }
          // fall through
          case 76: break;
          case 5:
            { handler.handleNothing("\n");
                                   saveLexState = YYINITIAL;
                                   yybegin(CLEAN);
            }
          // fall through
          case 77: break;
          case 6:
            { transposable = false;
                                   handler.handleNothing(" ");
            }
          // fall through
          case 78: break;
          case 7:
            { transposable = true;
                                   String str = yytext();
                                   if (commands.contains(str)) {
                                       yybegin(COMMANDS);
                                       handler.handleCommand(str);
                                   } else if (macros.contains(str)) {
                                       yybegin(COMMANDS);
                                       handler.handleMacro(str);
                                   } else if (localFun.contains(str)) {
                                        yybegin(COMMANDS);
                                        handler.handleFunctionId(str);
                                   } else {
                                       if (returnValues.contains(str) || argsValues.contains(str)) {
                                           handler.handleInputOutputArgs(str);
                                       }  else {
                                           handler.handleId(str);
                                       }
                                   }
            }
          // fall through
          case 79: break;
          case 8:
            { transposable = false;
                                   yybegin(QSTRING);
                                   handler.handleString("&#0034;");
            }
          // fall through
          case 80: break;
          case 9:
            { transposable = false;
                                   handler.handleSpecial(yytext());
            }
          // fall through
          case 81: break;
          case 10:
            { transposable = false;
                                   handler.handleOperator("&#0038;");
            }
          // fall through
          case 82: break;
          case 11:
            { if (transposable) {
                                       handler.handleOperator("&#0039;");
                                   } else {
                                       yybegin(QSTRING);
                                       handler.handleString("&#0039;");
                                   }
            }
          // fall through
          case 83: break;
          case 12:
            { transposable = false;
                                   handler.handleOpenClose(yytext());
            }
          // fall through
          case 84: break;
          case 13:
            { transposable = true;
                                   handler.handleOpenClose(yytext());
            }
          // fall through
          case 85: break;
          case 14:
            { transposable = false;
                                   handler.handleOperator(yytext());
            }
          // fall through
          case 86: break;
          case 15:
            { transposable = false;
                                   yybegin(FIELD);
                                   handler.handleOperator(yytext());
            }
          // fall through
          case 87: break;
          case 16:
            { transposable = true;
                                   handler.handleNumber(yytext());
            }
          // fall through
          case 88: break;
          case 17:
            { transposable = false;
                                   handler.handleOperator("&#0060;");
            }
          // fall through
          case 89: break;
          case 18:
            { transposable = false;
                                   handler.handleOperator("&#0062;");
            }
          // fall through
          case 90: break;
          case 19:
            { transposable = false;
                                   yybegin(YYINITIAL);
                                   handler.handleString("&#0034;");
            }
          // fall through
          case 91: break;
          case 20:
            { transposable = false;
                                   handler.handleString("&#0038;");
            }
          // fall through
          case 92: break;
          case 21:
            { transposable = false;
                                   yybegin(YYINITIAL);
                                   handler.handleString("&#0039;");
            }
          // fall through
          case 93: break;
          case 22:
            { transposable = false;
                                   handler.handleString("&#0060;");
            }
          // fall through
          case 94: break;
          case 23:
            { transposable = false;
                                   handler.handleString("&#0062;");
            }
          // fall through
          case 95: break;
          case 24:
            { handler.handleComment(yytext());
            }
          // fall through
          case 96: break;
          case 25:
            { if (breakstring) {
                                     saveLexState = QSTRING;
                                     breakstring = false;
                                   } else if (breakargs) {
                                     saveLexState = WHITESEOL;
                                     breakargs = false;
                                   } else {
                                     saveLexState = YYINITIAL;
                                   }
                                   handler.handleNothing("\n");
                                   yybegin(CLEAN);
            }
          // fall through
          case 97: break;
          case 26:
            { handler.handleComment("&#0034;");
            }
          // fall through
          case 98: break;
          case 27:
            { handler.handleComment("&#0038;");
            }
          // fall through
          case 99: break;
          case 28:
            { handler.handleComment("&#0039;");
            }
          // fall through
          case 100: break;
          case 29:
            { handler.handleComment("&#0060;");
            }
          // fall through
          case 101: break;
          case 30:
            { handler.handleComment("&#0062;");
            }
          // fall through
          case 102: break;
          case 31:
            { yypushback(1);
                                   yybegin(YYINITIAL);
            }
          // fall through
          case 103: break;
          case 32:
            { handler.handleField(yytext());
            }
          // fall through
          case 104: break;
          case 33:
            { yybegin(COMMANDSWHITE);
                                   handler.handleNothing("    ");
            }
          // fall through
          case 105: break;
          case 34:
            { yybegin(COMMANDSWHITE);
                                   handler.handleNothing(" ");
            }
          // fall through
          case 106: break;
          case 35:
            { yypushback(yylength());
                                   yybegin(YYINITIAL);
            }
          // fall through
          case 107: break;
          case 36:
            { handler.handleNothing("    ");
            }
          // fall through
          case 108: break;
          case 37:
            { handler.handleNothing(" ");
            }
          // fall through
          case 109: break;
          case 38:
            { id = yytext();
                                   yybegin(TYPEID);
            }
          // fall through
          case 110: break;
          case 39:
            { handler.handleOpenClose("[");
                                   yybegin(RETS);
            }
          // fall through
          case 111: break;
          case 40:
            { 
            }
          // fall through
          case 112: break;
          case 41:
            { localFun.add(id);
                                   handler.handleFunctionIdDecl(id);
                                   handler.handleOpenClose("(");
                                   yybegin(ARGS);
            }
          // fall through
          case 113: break;
          case 42:
            { returnValues.add(id);
                                   handler.handleInputOutputArgsDecl(id);
                                   handler.handleOperator("=");
                                   yybegin(FUNNAME);
            }
          // fall through
          case 114: break;
          case 43:
            { id = yytext();
                                   localFun.add(id);
                                   handler.handleFunctionIdDecl(id);
            }
          // fall through
          case 115: break;
          case 44:
            { handler.handleOpenClose("(");
                                   yybegin(ARGS);
            }
          // fall through
          case 116: break;
          case 45:
            { id = yytext();
                                   returnValues.add(id);
                                   handler.handleInputOutputArgsDecl(id);
            }
          // fall through
          case 117: break;
          case 46:
            { handler.handleDefault(", ");
            }
          // fall through
          case 118: break;
          case 47:
            { handler.handleOperator("=");
                                   yybegin(FUNNAME);
            }
          // fall through
          case 119: break;
          case 48:
            { handler.handleOpenClose("[");
            }
          // fall through
          case 120: break;
          case 49:
            { handler.handleOpenClose("]");
            }
          // fall through
          case 121: break;
          case 50:
            { id = yytext();
                                   argsValues.add(id);
                                   handler.handleInputOutputArgsDecl(id);
            }
          // fall through
          case 122: break;
          case 51:
            { handler.handleOpenClose(")");
                                   yybegin(YYINITIAL);
            }
          // fall through
          case 123: break;
          case 52:
            { handler.handleNothing("\n");
                                   saveLexState = WHITESEOL;
                                   yybegin(CLEAN);
            }
          // fall through
          case 124: break;
          case 53:
            { yypushback(1);
                                   yybegin(ARGS);
            }
          // fall through
          case 125: break;
          case 54:
            { whitesOnFirstLine = yylength();
                                   yybegin(YYINITIAL);
            }
          // fall through
          case 126: break;
          case 55:
            { yypushback(1);
                                   yybegin(saveLexState);
            }
          // fall through
          case 127: break;
          case 56:
            { int len = yylength() - whitesOnFirstLine;
                                   if (len > 0) {
                                      yypushback(len);
                                   }
                                   yybegin(saveLexState);
            }
          // fall through
          case 128: break;
          case 57:
            { handler.handleNothing("\n");
            }
          // fall through
          case 129: break;
          case 58:
            { transposable = true;
                                   handler.handleConstants(yytext());
            }
          // fall through
          case 130: break;
          case 59:
            { transposable = false;
                                   handler.handleOperator(".&#0039;");
            }
          // fall through
          case 131: break;
          case 60:
            { transposable = false;
                                   yypushback(2);
                                   yybegin(COMMENT);
            }
          // fall through
          case 132: break;
          case 61:
            { transposable = false;
                                   handler.handleOperator("&#0060;=");
            }
          // fall through
          case 133: break;
          case 62:
            { transposable = false;
                                   handler.handleOperator("&#0060;&#0062;");
            }
          // fall through
          case 134: break;
          case 63:
            { transposable = false;
                                   handler.handleOperator("&#0062;=");
            }
          // fall through
          case 135: break;
          case 64:
            { transposable = false;
                                   handler.handleSKeywords(yytext());
            }
          // fall through
          case 136: break;
          case 65:
            { localFun.add(id);
                                   handler.handleFunctionIdDecl(id);
                                   yypushback(yylength());
                                   yybegin(YYINITIAL);
            }
          // fall through
          case 137: break;
          case 66:
            { handler.handleSpecial(yytext());
                                   yybegin(BREAKINARGS);
            }
          // fall through
          case 138: break;
          case 67:
            { breakargs = true;
                                   yypushback(2);
                                   yybegin(COMMENT);
            }
          // fall through
          case 139: break;
          case 68:
            { handler.handleNothing("...");
            }
          // fall through
          case 140: break;
          case 69:
            { transposable = false;
                                   handler.handleCKeywords(yytext());
            }
          // fall through
          case 141: break;
          case 70:
            { transposable = false;
                                   handler.handleFKeywords("function");
                                   handler.handleNothing(" ");
                                   yybegin(FUNCTION);
            }
          // fall through
          case 142: break;
          case 71:
            { transposable = false;
                                   handler.handleFKeywords("function");
                                   handler.handleNothing(" ");
                                   handler.handleOpenClose("[");
                                   yybegin(RETS);
            }
          // fall through
          case 143: break;
          case 72:
            { transposable = false;
                                   returnValues.clear();
                                   argsValues.clear();
                                   handler.handleFKeywords("endfunction");
            }
          // fall through
          case 144: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
