// =============================================================================
// Scilab ( https://www.scilab.org/ ) - This file is part of Scilab
// Copyright (C) 2025 - Dassault Systèmes S.E. - Clément DAVID
//
// This file is distributed under the same license as the Scilab package.
// =============================================================================
//
// <-- XCOS TEST -->
// <-- NO CHECK REF -->
//
// <-- Non-regression test for bug 16739 -->
//
// <-- GitLab URL -->
// https://gitlab.com/scilab/scilab/-/issues/16739
//
// <-- Short Description -->
// labels boxes with relative positionning are not translated correctly
// Note: to do a visual check, uncomment the xcosDiagramExport lines below
//

// this file has been generated by Scilab 5.5.2
scs_m = xcosDiagramToScilab(SCI + "/modules/xcos/tests/nonreg_tests/issue_16739.zcos");
// xcosDiagramExport(scs_m, "issue_16739.png");

// compute the viewport
function viewport = compute_viewport(scs_m)
    min_orig = [-%eps -%eps];
    max_orig = [%eps %eps];
    for o = scs_m.objs
        if typeof(o) == "Block" then
            orig = o.graphics.orig;
            min_orig = min(min_orig, orig);
            max_orig = max(max_orig, orig);
        end
    end
    viewport = abs(max_orig - min_orig);
endfunction

// ensure the viewports are the same as in Scilab 5.5.2
assert_checktrue(compute_viewport(scs_m) <= ([1650 700] * 1.1))
expected_viewport = [   1470 430
                        1240 340
                        1300 250
                        1520 370
                        1640 420
                        1320 540
                         270 270
                        1780 580    ] * 1.1;
i = 1;
for o = scs_m.objs
    if typeof(o) == "Block" then
        if o.gui == "SUPER_f" then
            viewport = compute_viewport(o.model.rpar);
            // xcosDiagramExport(o.model.rpar, sprintf("issue_16739_%d.png", i));
            printf("%s %d %d\n", o.graphics.id, viewport);
            assert_checktrue(viewport <= expected_viewport(i, :));
            i = i + 1;
        end
    end
end
