/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.gui;


 /**
   * @author Calixte DENIZET
   */
public class ScilabTermination {

 /**
   * Constructor
   */
 protected ScilabTermination() {
    throw new UnsupportedOperationException();
 }
  public static void ScilabExit() {
    ScilabTerminationJNI.ScilabExit();
  }

}
